from .compare import Compare
from .edit_property import edit_property
from .homepage import HomePage
from .property_detail import PropertyDetail
from .property_list import property_list
from .property_listing import PropertyListing
from .property_manage import PropertyManage
from .sell import Sell
from .wishlist import WishlistView
