# Generated by Django 4.2.4 on 2025-02-13 14:17

import HomeBless.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBless', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'For Sale'), ('rent', 'For Rent')], default='buy', max_length=10),
        ),
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=HomeBless.models.seller_profile_picture_upload_path),
        ),
    ]
