# Generated by Django 5.1.7 on 2025-03-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBless', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='transaction_type',
            new_name='selling_type',
        ),
        migrations.AddField(
            model_name='property',
            name='seller_status',
            field=models.CharField(choices=[('owner', 'Owner'), ('agent', 'Agent')], default='owner', max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
