# Generated by Django 5.1.7 on 2025-03-31 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBless', '0002_rename_transaction_type_property_selling_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
    ]
