# Generated by Django 4.2.4 on 2025-02-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBless', '0003_alter_property_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='construct_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
