# Generated by Django 4.2.4 on 2025-03-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBless', '0004_property_construct_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decoration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flooring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='property',
            name='construct_date',
        ),
        migrations.AddField(
            model_name='property',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='backup_power',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='construct_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='drainage_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='electrical_system',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='hot_cold_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='safety_circuit_breaker',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='ceiling_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeBless.ceiling'),
        ),
        migrations.AddField(
            model_name='property',
            name='conditions',
            field=models.ManyToManyField(blank=True, to='HomeBless.propertycondition'),
        ),
        migrations.AddField(
            model_name='property',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeBless.decoration'),
        ),
        migrations.AddField(
            model_name='property',
            name='flooring',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeBless.flooring'),
        ),
        migrations.AddField(
            model_name='property',
            name='home_features',
            field=models.ManyToManyField(blank=True, to='HomeBless.homefeature'),
        ),
        migrations.AddField(
            model_name='property',
            name='project_amenities',
            field=models.ManyToManyField(blank=True, to='HomeBless.projectamenity'),
        ),
        migrations.AddField(
            model_name='property',
            name='views',
            field=models.ManyToManyField(blank=True, to='HomeBless.view'),
        ),
        migrations.AddField(
            model_name='property',
            name='wall_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeBless.wall'),
        ),
        migrations.AddField(
            model_name='property',
            name='warranties',
            field=models.ManyToManyField(blank=True, to='HomeBless.warranty'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='HomeBless.propertytype'),
        ),
    ]
