# Generated by Django 4.2.4 on 2025-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeBless', '0005_ceiling_decoration_flooring_homefeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.FloatField(),
        ),
    ]
